# Generated by Django 5.1.9 on 2025-05-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='users.staff'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='clauses',
            field=models.ManyToManyField(blank=True, related_name='contrats', to='hr.clausecontrat'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='users.staff'),
        ),
        migrations.AddField(
            model_name='paie',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paies', to='users.staff'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='users.staff'),
        ),
        migrations.AddField(
            model_name='pausejournaliere',
            name='pointage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='hr.pointage'),
        ),
    ]
