# Generated by Django 5.1.9 on 2025-05-28 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionadmintoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_auth_token', to='saas_admin.institutionadmin'),
        ),
    ]
