# Generated by Django 5.1.9 on 2025-05-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='users.eleve'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academic.niveau'),
        ),
        migrations.AddField(
            model_name='palier',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='academic.session'),
        ),
        migrations.AddField(
            model_name='classesession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.session'),
        ),
        migrations.AddField(
            model_name='specialite',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='academic.filiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.specialite'),
        ),
    ]
