from rest_framework.routers import DefaultRouter
from .views import (
    PreferenceUserViewSet, AnnonceViewSet, LuParAnnonceViewSet,
    ConfigurationClasseViewSet, configuration_complete,
    DispositionClasseViewSet, DispositionClasseFullViewSet,
    PlaceViewSet, DemandeChangementPlaceViewSet,
)
from django.urls import path

urlpatterns = [
    path('classes/full/<int:classe_session_id>/', configuration_complete, name='configuration-complete'),     
]

router = DefaultRouter()
router.register(r'annonces', AnnonceViewSet)
router.register(r'lectures', LuParAnnonceViewSet)

router.register(r'preferences', PreferenceUserViewSet, basename='preferences')

router.register(r'classes', ConfigurationClasseViewSet)
router.register(r'dispositions', DispositionClasseViewSet)
router.register(r'dispositions-full', DispositionClasseFullViewSet, basename='dispositions-full')
# Note: 'basename' is used to avoid conflicts with the default basename generated by the router
router.register(r'places', PlaceViewSet)
router.register(r'demandes-changement-place', DemandeChangementPlaceViewSet)
urlpatterns += router.urls
