# Generated by Django 5.1.9 on 2025-05-30 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Succursale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('est_siege', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('capacite', models.PositiveIntegerField()),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='infrastructure.batiment')),
            ],
        ),
        migrations.AddField(
            model_name='batiment',
            name='succursale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='infrastructure.succursale'),
        ),
    ]
