# Generated by Django 5.1.9 on 2025-05-30 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teaching', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteconfig',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_configs', to='users.staff'),
        ),
        migrations.AddField(
            model_name='noteconfig',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='teaching.matiere'),
        ),
        migrations.AddField(
            model_name='presence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='users.eleve'),
        ),
        migrations.AddField(
            model_name='presence',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='teaching.evenement'),
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='domaines',
            field=models.ManyToManyField(blank=True, related_name='unites_enseignement', to='teaching.domaine'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='teaching.uniteenseignement'),
        ),
    ]
