# Generated by Django 5.1.9 on 2025-05-28 18:08

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('PREPRIMAIRE', 'Pré-primaire'), ('PRIMAIRE', 'primaire'), ('COLLEGE', 'collège'), ('LYCEE', 'lycée'), ('FORMATION', 'Ecole de formation'), ('UNIVERSITE', 'Université')], default='ECOLE', max_length=20)),
                ('type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVE', 'Privé'), ('PARPUBLIC', 'Parapublic')], default='PUBLIC', max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('tel2', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('on_trial', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='institutions.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
